//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Answer
    {
        public int ID { get; set; }
        public string BodyJSON { get; set; }
        [Display(Name = "回答日時")]
        public Nullable<System.DateTime> Answered { get; set; }
    
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual ParticipantUserProject ParticipantUserProject { get; set; }
    }
}
