//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid ID { get; set; }
        public System.DateTime Uploaded { get; set; }
        public byte[] BinaryData { get; set; }
        public string FileExtension { get; set; }
        public virtual User User { get; set; }
    }
}
