//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duration
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }

        //モデルファーストからコードファーストに切り替えたときに下記エラーが出たため、
        //双方向のナビゲーションプロパティを一方向に変更した。

        //追加情報:型 'NihonUnisys.Olyzae.Models.Duration' と 'NihonUnisys.Olyzae.Models.Thread' の間のアソシエーションのプリンシパル End を特定できません。
        //relationship fluent API またはデータ注釈を使用して、このアソシエーションのプリンシパル End を明示的に構成する必要があります。

        //public virtual Thread Thread { get; set; }
        //public virtual Project Project { get; set; }
        //public virtual Theme Theme { get; set; }
    }
}
