//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class GroupWork
    {
        /// <summary>
        /// Themeプロパティの外部キー。
        /// </summary>
        /// <remarks>
        /// 複合主キーを構成します。
        /// </remarks>
        [Key]
        [Column("Theme_ID", Order = 0)]
        public int ThemeID { get; set; }

        /// <summary>
        /// ProjectGroupプロパティの外部キー。
        /// </summary>
        /// <remarks>
        /// 複合主キーを構成します。
        /// </remarks>
        [Key]
        [Column("ProjectGroup_ID", Order = 1)]
        public int ProjectGroupID { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string EvaluationJSON { get; set; }

        public Guid? AttachedDocumentID { get; set; }

        [Display(Name = "提出ファイル名")]
        public string AttachedFileName { get; set; }

        [Required]
        [Display(Name = "状況")]
        public GroupWorkStatus Status { get; set; }

        public Evaluations.Evaluation Evaluation
        {
            get
            {
                var json = this.EvaluationJSON;
                if (json == null)
                {
                    return null;
                }
                try
                {
                    var evaluation = Evaluations.Evaluation.FromJsonString(json);
                    return evaluation;
                }
                catch (Exception ex)
                {
                    string message = "プロパティ 'EvaluationJSON' に不正な値が格納されています。\r\n"
                        + "ThemeID: " + this.ThemeID.ToString() + "\r\n"
                        + "ProjectGroupID: " + this.ProjectGroupID.ToString() + "\r\n"
                        + "EvaluationJSON: '" + this.EvaluationJSON + "'";
                    throw new InvalidOperationException(message, ex);
                }
            }
        }

        public int? EvaluationValue(string key)
        {
            var ev = this.Evaluation;
            if (ev == null || ev.items == null) return null;
            return ev.items
                .Where(x => x.name == key)
                .Select(x => x.value)
                .FirstOrDefault();
        }

        [ForeignKey("ThemeID")]
        public virtual Theme Theme { get; set; }

        [Display(Name = "グループ")]
        [ForeignKey("ProjectGroupID")]
        public virtual ProjectGroup ProjectGroup { get; set; }
    }
}
