//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MentorUser : User
    {
        public MentorUser()
        {
            this.Projects = new HashSet<MentorUserProject>();
        }
    
    
        public virtual ICollection<MentorUserProject> Projects { get; set; }

        public override string Role
        {
            get { return "MentorUser"; }
        }
    }
}
