//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Message
    {
        public Message()
        {
            this.ReceivedUsers = new HashSet<UserMessage>();
        }
    
        public int ID { get; set; }

        public Nullable<System.DateTime> Sent { get; set; }

        [DataType(DataType.MultilineText)]
        [Required]
        public string Body { get; set; }

        public string BodySummary
        {
            get
            {
                const int length = 70;
                var body = this.Body;
                if (body == null)
                {
                    return null;
                }
                return (body.Length <= length)
                    ? body
                    : body.Substring(0, length) + "...";
            }
        }

        public Guid? AttachedDocumentID { get; set; }
        public string AttachedFileName { get; set; }

        public virtual User SentUser { get; set; }
        public virtual Thread Thread { get; set; }
        public virtual ICollection<UserMessage> ReceivedUsers { get; set; }
    }
}
