//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    
    public enum ProjectStatus : int
    {
        Default = 0,
        Accepting = 1,
        Accepted = 2,
        Holding = 5,
        Held = 6,
        Cancelled = 9,
        Expired = 99
    }
}
