//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectPage
    {
        public ProjectPage()
        {
            this.PageContents = new HashSet<PageContent>();
        }
    
        public int ID { get; set; }
        public string PageJSON { get; set; }
        public System.DateTime Created { get; set; }

        [Required]
        public virtual Project Project { get; set; }
        public virtual ICollection<PageContent> PageContents { get; set; }

        public ProjectPages.PageBody PageBody
        {
            get
            {
                if (this.PageJSON == null)
                {
                    return null;
                }
                try
                {
                    var page = ProjectPages.PageBody.FromJsonString(this.PageJSON);
                    return page;
                }
                catch (Exception ex)
                {
                    string message = "プロパティ 'PageJSON' に不正な値が格納されています。\r\n"
                        + "Id: " + this.ID.ToString() + "\r\n"
                        + "PageJSON: '" + this.PageJSON + "'";
                    throw new InvalidOperationException(message, ex);
                }
            }
        }

        public void UpdatePageBody(ProjectPages.PageBody pageBody)
        {
            this.PageJSON = (pageBody == null) ? null : pageBody.ToString();
        }
    }
}
