//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectGroup : Group
    {
        public ProjectGroup()
        {
            this.GroupWork = new HashSet<GroupWork>();
        }

        [Display(Name = "公開範囲")]
        [Required]
        public ProjectGroupAccessibility? Accessibility { get; set; }

        public virtual Project Project { get; set; }
        public virtual ICollection<GroupWork> GroupWork { get; set; }
    }
}
