//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    
    public partial class Questionnaire
    {
        public Questionnaire()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public int ID { get; set; }
        [Display(Name = "名前")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "配信日時")]
        public Nullable<System.DateTime> Questioned { get; set; }
        public string BodyJSON { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<Answer> Answer { get; set; }
    }
}
