//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NihonUnisys.Olyzae.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class Theme
    {
        public Theme()
        {
            this.GroupWork = new HashSet<GroupWork>();
        }
    
        public int ID { get; set; }
        [Required]
        [Display(Name = "名前")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "説明")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    
        public virtual Duration Duration { get; set; }
        public virtual Project Project { get; set; }

        /// <summary>
        /// 課題の評価軸を格納するJSON文字列を取得または設定します。
        /// </summary>
        public string EvaluationJSON { get; set; }

        [Display(Name = "評価項目")]
        public string[] EvaluationKeys
        {
            get
            {
                var evaluation = this.Evaluation;
                if (evaluation == null)
                {
                    return new string[0];
                }
                return evaluation.items.Select(x => x.name).ToArray();
            }
        }

        public Evaluations.Evaluation Evaluation
        {
            get
            {
                var json = this.EvaluationJSON;
                if (json == null)
                {
                    return null;
                }
                try
                {
                    var evaluation = Evaluations.Evaluation.FromJsonString(json);
                    return evaluation;
                }
                catch (Exception ex)
                {
                    string message = "プロパティ 'EvaluationJSON' に不正な値が格納されています。\r\n"
                        + "Id: " + this.ID.ToString() + "\r\n"
                        + "EvaluationJSON: '" + this.EvaluationJSON + "'";
                    throw new InvalidOperationException(message, ex);
                }
            }
        }

        public void UpdateEvaluation(Evaluations.Evaluation evaluation)
        {
            this.EvaluationJSON = (evaluation == null) ? null : evaluation.ToString();
        }

        public virtual ICollection<GroupWork> GroupWork { get; set; }
    }
}
